directories:
  output: release
  buildResources: build
appId: com.focusarena.desktop
productName: Focus Arena
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
files: []
electronVersion: 40.4.1
